class Food {
  String? imgUrl;
  String? desc;
  String? name;
  String? waitTIme;
  num? score;
  String? cal;
  num? price;
  num? quantity;

  String? about;
  bool highLight;
  Food(
      {this.imgUrl,
      this.desc,
      this.name,
      this.waitTIme,
      this.score,
      this.cal,
      this.price,
      this.quantity,
      this.about,
      this.highLight = false});
  static List<Food> generateRecommendFoods() {
    return [
      Food(
        imgUrl: 'assets/images/dish1.png',
        desc: 'Medium',
        name: 'Mexican Panini',
        waitTIme: '10min',
        score: 4.8,
        cal: '325 Kcal',
        price: 90,
        quantity: 1,
        about:
            'Panini is basically a sandwich but is made with not the regular bread recipe. A panino or panini is a sandwich made using Italian bread.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish2.png',
        desc: 'Medium',
        name: 'Aloo Tikki Burger',
        waitTIme: '10min',
        score: 4.2,
        cal: '300 Kcal',
        price: 80,
        quantity: 1,
        about:
            'The combination of a potato and peas patty with special Indian spices coated with breadcrumbs, served with sweet tomato mayo, fresh onions, and tomatoes in a regular bun.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish3.png',
        desc: 'Light',
        name: 'Veggie Burger',
        waitTIme: '15min',
        score: 4.8,
        cal: '250 Kcal',
        price: 60,
        quantity: 1,
        about:
            'These burgers are made from ingredients like beans, especially soybeans and tofu, nuts, grains, seeds or fungi such as mushrooms or mycoprotein.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish4.png',
        desc: 'Heavy',
        name: 'Paneer Toast',
        waitTIme: '5min',
        score: 4.8,
        cal: '380 Kcal',
        price: 80,
        quantity: 1,
        about:
            ' Cheese on toast is made by placing paneer and sliced or grated cheese on toasted bread and melting it under a grill.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish5.png',
        desc: 'Heavy',
        name: 'Cheese Veg Club',
        waitTIme: '15min',
        score: 4.5,
        cal: '300 Kcal',
        price: 60,
        quantity: 1,
        about:
            'Scrumptious vegetarian Club sandwich with a unique twist making it different from traditional club sandwiches',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish6.png',
        desc: 'Heavy',
        name: 'Double Cheese Pizza',
        waitTIme: '20min',
        score: 4.1,
        cal: '380 Kcal',
        price: 90,
        quantity: 1,
        about: ' Best for a brunch.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish7.png',
        desc: 'Light',
        name: 'Veg Puff',
        waitTIme: '5min',
        score: 4.8,
        cal: '200 Kcal',
        price: 50,
        quantity: 1,
        about: ' Get the taste eating healthy.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish8.png',
        desc: 'Heavy',
        name: 'Cheese Garlic Bread',
        waitTIme: '10min',
        score: 4.8,
        cal: '300 Kcal',
        price: 60,
        quantity: 1,
        about:
            ' It is typically made using a French baguette, or sometimes a sourdough like ciabatta which is partially sliced downwards, allowing the condiments to soak into the loaf while keeping it in one piece.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish9.png',
        desc: 'Light',
        name: 'Cold Coffee',
        waitTIme: '2min',
        score: 3.9,
        cal: '150 Kcal',
        price: 40,
        quantity: 1,
        about: ' Refresh yourself.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish10.png',
        desc: 'Light',
        name: 'Milk Shake',
        waitTIme: '2min',
        score: 4.0,
        cal: '200 Kcal',
        price: 35,
        quantity: 1,
        about:
            ' Made by mixing milk, ice cream, and sweet syrups like chocolate syrup.',
        highLight: false,
      )
    ];
  }

  static List<Food>? generatePopularFood() {
    return [
      Food(
          imgUrl: 'assets/images/dish11.png',
          desc: 'Light',
          name: 'Strawberry Juice',
          waitTIme: '5min',
          score: 4.2,
          cal: '250 Kcal',
          price: 50,
          quantity: 1,
          about:
              'Support healthy skin, strengthen the immune system, lower blood pressure, increase blood circulation, and prevent birth defects.',
          highLight: false),
      Food(
          imgUrl: 'assets/images/dish12.png',
          desc: 'Light',
          name: 'Kiwi Juice',
          waitTIme: '10min',
          score: 4.5,
          cal: '200 Kcal',
          price: 65,
          quantity: 1,
          about:
              'Contains heart-healthy benefits, including reducing the risk of clots and reducing blood pressure levels.',
          highLight: false),
      Food(
        imgUrl: 'assets/images/dish13.png',
        desc: 'Medium',
        name: 'Chocolate Milkshake',
        waitTIme: '10min',
        score: 3.9,
        cal: '250 Kcal',
        price: 60,
        quantity: 1,
        about: ' Proteins are there in Milkshakes which make our bones strong.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish14.png',
        desc: 'Light',
        name: 'Pineapple Juice',
        waitTIme: '10min',
        score: 3.9,
        cal: '200 Kcal',
        price: 45,
        quantity: 1,
        about:
            ' It is high in vitamin C, which can help protect your body against the common cold. It also contains enzymes that have been shown to activate a healthy immune system response.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish15.png',
        desc: 'Light',
        name: 'Orange Juice',
        waitTIme: '5min',
        score: 4.1,
        cal: '200 Kcal',
        price: 45,
        quantity: 1,
        about:
            '  The humble orange and its juice are also great snacking options for being low of calories and boosting instant energy and power.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish16.png',
        desc: 'Medium',
        name: 'Oreo Shake',
        waitTIme: '5min',
        score: 4.8,
        cal: '250 Kcal',
        price: 50,
        quantity: 1,
        about:
            'Oreo shake is full of potassium, as well as calcium, Vitamin C, and fiber.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish17.png',
        desc: 'Light',
        name: 'Grape Juice',
        waitTIme: '5min',
        score: 4.0,
        cal: '200 Kcal',
        price: 45,
        quantity: 1,
        about:
            'It contains most of the vitamins and minerals found in table grapes, plus the health benefits of the nutrient-rich seeds.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish18.png',
        desc: 'Light',
        name: 'Apple Juice',
        waitTIme: '10min',
        score: 3.9,
        cal: '200 Kcal',
        price: 45,
        quantity: 1,
        about:
            ' It is typically made using a French baguette, or sometimes a sourdough like ciabatta which is partially sliced downwards, allowing the condiments to soak into the loaf while keeping it in one piece.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish19.png',
        desc: 'Light',
        name: 'Raspberry Juice',
        waitTIme: '5min',
        score: 4.9,
        cal: '200 Kcal',
        price: 60,
        quantity: 1,
        about:
            'The nutrients contained inside the fruit help you with blood circulation and digestion health.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish20.png',
        desc: 'Medium',
        name: 'Chikoo Shake ',
        waitTIme: '10min',
        score: 4.8,
        cal: '250 Kcal',
        price: 50,
        quantity: 1,
        about:
            'Rich in essential nutrients, minerals, vitamins A & C and antioxidants.',
        highLight: false,
      ),
    ];
  }

  static List<Food>? generateSweetSpot() {
    return [
      Food(
          imgUrl: 'assets/images/dish21.png',
          desc: 'Light',
          name: 'Cold Bournvita',
          waitTIme: '5min',
          score: 4.2,
          cal: '150 Kcal',
          price: 40,
          quantity: 1,
          about:
              'Contains Vitamin D, which increases the absorption of calcium from milk.',
          highLight: false),
      Food(
          imgUrl: 'assets/images/dish22.png',
          desc: 'Light',
          name: 'Bread Butter',
          waitTIme: '5min',
          score: 3.5,
          cal: '200 Kcal',
          price: 40,
          quantity: 1,
          about:
              'One slice of bread with butter provides up 20 percent of the recommended daily intake of vitamin D, and it also serves as a good source of calcium, vitamin B-6, magnesium, iron, vitamin B-12, niacin and zinc, with 10 percent of the amount of these nutrients you need in a day.',
          highLight: false),
      Food(
        imgUrl: 'assets/images/dish23.png',
        desc: 'Medium',
        name: 'Thepla',
        waitTIme: '10min',
        score: 4.3,
        cal: '200 Kcal',
        price: 25,
        quantity: 1,
        about:
            'Thepla burns the excess calories and helps you in staying energized. Good for skin, eyes, and hair –the nutrients and vitamins present in Thepla help to promote glowing and healthy skin. It is also good for the eyes, liver, and nerves.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish24.png',
        desc: 'Medium',
        name: 'Cheese Pasta',
        waitTIme: '10min',
        score: 4.0,
        cal: '300 Kcal',
        price: 80,
        quantity: 1,
        about: 'Provides glucose, the crucial fuel for your brain and muscles.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish25.png',
        desc: 'Medium',
        name: 'Potato Puff',
        waitTIme: '10min',
        score: 4.4,
        cal: '250 Kcal',
        price: 20,
        quantity: 1,
        about:
            'Feeling full but want to eat something? Potato puff is all you need.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish26.png',
        desc: 'Medium',
        name: 'Fries Masala',
        waitTIme: '5min',
        score: 3.8,
        cal: '250 Kcal',
        price: 50,
        quantity: 1,
        about:
            'Masala fries produce lower blood glucose and insulin levels in children',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish27.png',
        desc: 'Medium',
        name: 'Maggie',
        waitTIme: '2min',
        score: 3.5,
        cal: '200 Kcal',
        price: 40,
        quantity: 1,
        about: 'Best choice when you are short of time.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish28.png',
        desc: 'Light',
        name: 'Italian Pizza',
        waitTIme: '10min',
        score: 4.3,
        cal: '300 Kcal',
        price: 80,
        quantity: 1,
        about:
            'Great source of nutrients. It provides high percentages of the total daily intake of protein, fat, saturated fat, fibre, calcium and lycopene.',
        highLight: false,
      ),
    ];
  }

  static List<Food>? generateShreeji() {
    return [
      Food(
          imgUrl: 'assets/images/dish29.png',
          desc: 'Light',
          name: 'Veg Sandwich',
          waitTIme: '5min',
          score: 4.2,
          cal: '150 Kcal',
          price: 20,
          quantity: 1,
          about: 'Most suitable food for breakfast.',
          highLight: false),
      Food(
          imgUrl: 'assets/images/dish30.png',
          desc: 'Heavy',
          name: 'Gujarati Thaali',
          waitTIme: '15min',
          score: 4.0,
          cal: '300 Kcal',
          price: 90,
          quantity: 1,
          about: 'Feels like home.',
          highLight: false),
      Food(
        imgUrl: 'assets/images/dish31.png',
        desc: 'Heavy',
        name: 'Punjabi Thaali',
        waitTIme: '15min',
        score: 4.3,
        cal: '300 Kcal',
        price: 100,
        quantity: 1,
        about: 'Who needs a restaurant when you have Shreeji.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish32.png',
        desc: 'Heavy',
        name: 'South Indian Meal',
        waitTIme: '20min',
        score: 4.0,
        cal: '300 Kcal',
        price: 80,
        quantity: 1,
        about: 'Not so found of spicy food? South Indian meal is for you.',
        highLight: false,
      ),
      Food(
        imgUrl: 'assets/images/dish33.png',
        desc: 'Medium',
        name: 'Manchurian',
        waitTIme: '10min',
        score: 4.4,
        cal: '250 Kcal',
        price: 80,
        quantity: 1,
        about: 'Spicy Chinese is love.',
        highLight: false,
      ),
    ];
  }
}
